from __future__ import annotations

import logging

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from prometheus_client import CONTENT_TYPE_LATEST, generate_latest

from app.api.v1.routers.auth import router as auth_router
from app.api.v1.routers.confluence import router as confluence_router
from app.api.v1.routers.documents import router as documents_router
from app.api.v1.routers.extraction import router as extraction_router
from app.api.v1.routers.knowledge_products import router as knowledge_products_router
from app.core.telemetry import setup_telemetry

logger = logging.getLogger(__name__)

app = FastAPI(title="Knowledge Product Studio API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3002"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Without this, Starlette's default 500 response is generated by
    ServerErrorMiddleware, which sits *outside* CORSMiddleware in the stack —
    so it never gets CORS headers added, and browsers report a generic
    network failure instead of showing the actual error. Registering a
    handler here routes the response back through ExceptionMiddleware
    (inside CORSMiddleware), so error responses behave like any other."""
    logger.exception("Unhandled exception on %s %s", request.method, request.url.path)
    return JSONResponse(status_code=500, content={"detail": "Internal server error"})

app.include_router(knowledge_products_router, prefix="/api/v1")
app.include_router(confluence_router, prefix="/api/v1")
app.include_router(extraction_router, prefix="/api/v1")
app.include_router(documents_router, prefix="/api/v1")
app.include_router(auth_router, prefix="/api/v1")

setup_telemetry(app)


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}


@app.get("/metrics")
async def metrics() -> Response:
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)
